# To compile for x86 (androVM)
# make ARCH=x86 -C /path/to/goldfish/  M=$(pwd) modules
#
# To cross compile for arm
# export PATH=$PATH:..../prebuilts/gcc/linux-x86/arm/arm-linux-androideabi-4.x/bin
# make CROSS_COMPILE=arm-linux-androideabi- ARCH=arm -C /path/to/goldfish/  M=$(pwd) modules
#
obj-m := droidcon.o
